name: fitness_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # CORRECTED Assets Section
  assets:
    - assets/Icons/  # This will include all files in the Icons folder

  # REMOVE the fonts section for now (unless you actually have the font file)
fonts:
    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing-font-5x7.otf